---
environments:
- name: Test
  domain: test.example.com
  foundations:
  - api1.example.com
  - api2.example.com
- name: Prod
  domain: example.com
  foundations:
  - api3.example.com
  - api4.example.com
